### PR TITLE
Updated Live Demo Links

### PR DESCRIPTION
**Pull request by phillc73**
As Spark and Glimmer hosting are no longer available, the Live Demo link for example 01-basic was broken. I uploaded this example, plus demos 02, 03 and 04, to my shinyapps.io account, then updated the README links.

Demo 01-basic was also failing due to selectionID. Removing this allowed the demo to run.

Unfortunately, the demo link on the trestletech ShinyAce website is still broken, as I have no access to update this. (http://trestletech.github.io/shinyAce/)

### CODE REVIEW

**Comment by trestletech** [comment]
Hey thanks for taking the time. This looks good.

I'd actually feel more comfortable if you removed the links from examples 2/3/4, though, since I advise people on the page not to host those publicly. Hosting them on ShinyApps.io might not be the end of the world since apps are containerized, but it may be possible for users to go in and edit the code of the application to add a redirect to a malicious page or something. I'd have to think about it to confirm, but either way I'd feel more comfortable not sending users to those apps.

If you can remove those links on 2/3/4, I'll go ahead and merge. Thanks again!

**Comment by trestletech** [comment]
Fixed gh-pages here: https://github.com/trestletech/shinyAce/commit/b8e7a48051dd63e9ab5a8cacc5c302bfddc00ba9

**Comment by phillc73** [comment]
No problem. Extra links removed. I can see your point about malicious code. I'd actually like to offer something similar to 02-eval to a specific subscriber base, hosted on shinyapps.io, as a private app protected by username and password. I'm still thinking about the security implications and am considering disabling all "system" calls from R code as a start.

**Comment by trestletech** [comment]
:+1: Thanks again!

**Pull request merged**
