### PR TITLE
[Completion] Fix AutoCompleteList in Constructor

### LINKED ISSUE #48: autoCompleteList in aceEditor can not work
```
library(shiny)
library(shinyAce)

shinyApp(
    ui = basicPage(
      aceEditor("mySmartEditor", "plot(wt ~ mpg, data=mtcars)", mode="r",
                autoComplete="live",
                autoCompleteList=list(mtcars=colnames(mtcars))), # can not work
      aceEditor("mySmartEditor2", "plot(wt ~ mpg, data=mtcars)", mode="r",
                autoComplete="live",
                autoCompleteList=list(mtcars=colnames(mtcars)))        
    ), # can anto complete
    
    server = function(session, input, output) {

      observe({
        comps <- list(mtcars = colnames(mtcars), airquality = colnames(airquality))
        updateAceEditor(session, "mySmartEditor2", autoCompleteList = comps)
      })
      
    }
)
```

Many thanks!

### PR DESCRIPTION
**Pull request by saurfang**
HTML data-* attributes in htmltools no longer automatically converts to JSON from list and attribute key is converted to lower cases. This commit changes the attribute name to lower case and perform explicit JSON conversion. The example has also been fixed for the error that anonymous function needs wrapping braces.

Fixes #48

### CODE REVIEW

**Comment by vnijs** [comment]
Thanks @saurfang! I will review and merge tomorrow. Any chance you could add one (or more) simple tests to help safeguard against similar changes (e.g., in htmltools or even jsonlite) in the future?

**Comment by vnijs** [comment]
@saurfang Here is an example of (2) in my previous comment. `fun1` and `fun2` are shown when `autoCompleteList` is provided in the call to `aceEditor`. `fun1` and `fun2` are not available when the  `observe` is used however.

For (1) it seems it should be possible to ignore "local" suggestions in Ace (see link below) but I wasn't clear on the implementation in R / Shiny. Any ideas?

https://stackoverflow.com/questions/41085240/is-there-a-way-to-remove-all-the-default-autocomplete-suggestions

```
library(shiny)
library(shinyAce)

shinyApp(
  ui = basicPage(
    aceEditor(
      "auto_editor", 
      "plot(wt ~ mpg, data=mtcars)\n", 
      mode = "r",
      autoComplete = "live",
      autoCompleteList = list(test = c("fun1", "fun2"))
    )
  ), 
  server = function(session, input, output) { 
    ## without the observe below 'fun1' and 'fun2' are shown
    ## however with the observe they are not available
    observe({
      comps <- list(mtcars = colnames(mtcars), airquality = colnames(airquality))
      shinyAce::updateAceEditor(session, "auto_editor", autoCompleteList = comps)
    })
  }
)
```

**Comment by vnijs** [comment]
Did you post something about the SQL editor already? I seem to recall seeing something about it but didn't see it on your GitHub page. Sounds really interesting!

Parsing the yaml with R is easy enough and passing it to the completer works fine as well. Is it already possible to turn off the local completer with the currently available code or would it require additional JS?

**Comment by saurfang** [comment]
That thing was still very much a work in progress so I made it to private for the time being. I just put out a PR to unblock you but it might need a bit more work to be releasable quality.

**Comment by vnijs** [comment]
Sounds really nice! Will look in detail tomorrow. FYI based on a quick tryout I noticed the message below when using `examples/06-autocomplete` ...

image

**Comment by saurfang** [comment]
oops. that particular one should be fixed now.

**Comment by vnijs** [comment]
The example seems to work now!

**Pull request merged**
