### PR TITLE
Update CRAN version of shinyAce

### PR DESCRIPTION
**Pull request by vnijs**
This PR attempts to address the concerns listed in issue #26. The remaining notes from R-check (3.2.3) are:

* checking installed package size ... NOTE
  installed size is  9.9Mb
  sub-directories of 1Mb or more:
    www   9.7Mb

* checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: ‘utils:::.win32consoleCompletion’
  See the note in ?`:::` about the use of this operator.

### CODE REVIEW

**Comment by trestletech** [comment]
Thanks so much for looking at this! 

I just submitted a PR to your branch that will clean up a few remaining loose ends and will hopefully be good enough to get back onto CRAN.

Let me know if the stacked PR thing causes problems. If so I can just close this and merge my branch that includes these fixes.

**Comment by trestletech** [comment]
I'm going to let this soak for a couple of days to make sure nobody reports any show-stopping issues. But if you haven't heard back from me by early next week, feel free to ping me on this again and we'll try to get it up on CRAN next week.

Thanks again!

**Comment by vnijs** [comment]
Excellent! Thanks Jeff.

**Comment by vnijs** [comment]
You said to ping you so ... ping. Any updates?

**Pull request merged**
